# 数据库
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3307/fang?useUnicode=true&characterEncoding=utf-8?serverTimezone=UTC
spring:
  datasource.url: jdbc:p6spy:mysql://localhost:3308/fang?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  datasource.driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#  datasource.url: jdbc:mysql://localhost:3307/fang?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#  datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  datasource.username: root
  datasource.password: root

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations:
    - classpath:/mapper/**.xml

# 设置单个文件最大内存
multipart:
  maxFileSize: 50Mb
  # 设置所有文件最大内存
  maxRequestSize: 50Mb
web:
  # 自定义文件上传路径
  upload-path: D:/picture/
  # 显示图片的路径
  image-path: http://localhost:8080/images/